name: Notify Release

on:
  workflow_dispatch:

env:
  GIT_PREVIOUS_SUCCESSFUL_COMMIT: ${{ github.event.before }}

jobs:
  build:
    uses: Crazy-Crew/.github/.github/workflows/notify.yml@main

    with:
      status: "release"
      branch: main

    secrets:
      webhook: ${{ secrets.BUILD_WEBHOOK }}