name: Snapshot Build
on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[ci-skip]')"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew build --stacktrace
      - name: Publish to Modrinth
        run: ./gradlew modrinth --stacktrace
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          COMMIT_MESSAGE: ${{ join(github.event.commits.*.message, '<br>') }}
      - name: Publish to Hangar
        run: ./gradlew publishAllPublicationsToHangar --stacktrace
        env:
          HANGAR_KEY: ${{ secrets.HANGAR_TOKEN }}
          COMMIT_MESSAGE: ${{ join(github.event.commits.*.message, '<br>') }}
      - name: Notify Discord
        if: success()
        run: ./gradlew dev-build --stacktrace
        env:
          BUILD_WEBHOOK: ${{ secrets.BUILD_WEBHOOK }}