name: '${name}'
main: '${group}.${name}'

authors:
  - ryderbelserion
  - BadBones69
  - TDL

version: '${version}'
api-version: '${minecraft}'
description: '${description}'
folia-supported: true

website: '${website}'

softdepend:
  - WorldGuard
  - WorldEdit
  - PlotSquared
  - SuperiorSkyBlock
  - GriefPrevention
  - Towny
  - Factions
  - Lands
  - StackMob
  - Vault
  - Oraxen
  - MCMMO

permissions:
  crazyenchantments.player.*:
    default: false
    children:
      crazyenchantments.tinker: true
      crazyenchantments.blacksmith: true
      crazyenchantments.gkitz: true
      crazyenchantments.gui: true
      crazyenchantments.limit: true
      crazyenchantments.info: true

  crazyenchantments.admin.*:
    default: false
    children:
      crazyenchantments.bypass.limit: true
      crazyenchantments.bypass.aura: true
      crazyenchantments.bypass.wings: true
      crazyenchantments.bypass.gkitz: true
      crazyenchantments.bypass.protectioncrystal: true
      crazyenchantments.admin: true

  crazyenchantments.admin:
    default: false

  crazyenchantments.bypass.limit:
    default: false

  crazyenchantments.bypass.aura:
    default: false

  crazyenchantments.bypass.wings:
    default: false

  crazyenchantments.bypass.gkitz:
    default: false

  crazyenchantments.bypass.protectioncrystal:
    default: false